### ISSUE TITLE
Tools / Admin Issues

### ISSUE THREAD

**Issue by UpperCenter** [ponydevs/pixel.horse#111]
## Going to bundle this into a 2 in one.

I'm trying to get the Admin service to run on my prod environment, because as it stands I can't kick / ban people or perform any admin commands.

Wack thing is that it works fine on my test env, copying it over seems to have broken it. I just get redirected to `/`.

I assumed this was a permission error, but I've given my account every role possible, and I still can't access it. I also have a ``location`` block setup in my NGINX config to allow for a connection. 

Secondly, trying to setup ``/tools`` on my dev server throws up this node error in the CLI every time I refresh the page (Page says Internal Server Error)

```bash
GET /tools 500 21.276 ms - 148
Error: Failed to deserialize user out of session
    at pass (/var/www/dergun.town/node_modules/passport/lib/authenticator.js:344:19)
    at Authenticator.deserializeUser (/var/www/dergun.town/node_modules/passport/lib/authenticator.js:362:5)
    at SessionStrategy.authenticate (/var/www/dergun.town/node_modules/passport/lib/strategies/session.js:60:10)
    at attempt (/var/www/dergun.town/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/var/www/dergun.town/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/var/www/dergun.town/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/dergun.town/node_modules/express/lib/router/route.js:137:13)
    at initialize (/var/www/dergun.town/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/var/www/dergun.town/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/dergun.town/node_modules/express/lib/router/route.js:137:13)
    at /var/www/dergun.town/node_modules/express-session/index.js:495:7
    at promise.then.res (/var/www/dergun.town/node_modules/connect-mongo/src/index.js:9:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

Any ideas? I've done a full rebuild and ``npm install`` to no avail.

**Comment by Tschrock** [comment]
Some ideas:
 - Make sure you're going to `/admin/` and not `/admin`
 - Clear the cache and cookies in your browser - that should reset your session.

**Comment by UpperCenter** [comment]
Thanks for the hot tip of ``/admin/``, that's working now. I can now access the web admin panel, but in game options like kicking or muting players, those options still seem missing.

**Comment by Tschrock** [comment]
the in-game mod tools were fixed in commit https://github.com/ponydevs/pixel.horse/commit/c9280e34677af5188d380c4ca544f91ee1363c4d
You'll want to add that change to get them working
